"""
Complete ingredient database for ALL 118 products - PRODUCTION READY
Uses centralized classification system for consistency
"""

from routes.ingredient_database import classify_ingredient as get_classification

def create_ingredient_item(name, custom_classification=None, custom_note=None, custom_regulatory=None):
    """Create standardized ingredient item using centralized classification"""
    
    # Always use centralized classification for consistency
    classification_data = get_classification(name)
    
    # Use custom values if provided, otherwise use centralized data
    classification = custom_classification or classification_data['classification']
    note = custom_note or classification_data['one_line_note']
    regulatory = custom_regulatory or classification_data['regulatory_note']
    
    return {
        "name": name,
        "classification": classification,
        "one_line_note": note,
        "regulatory_note": regulatory
    }

# COMPLETE INGREDIENT DATABASE FOR ALL 118 PRODUCTS
FULL_INGREDIENTS = {
    # BISCUITS & COOKIES
    "parle-g": [
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Sodium Metabisulphite"),
    ],
    
    "britannia-good-day": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Butter"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Sodium Metabisulphite"),
        create_ingredient_item("Artificial Butter Flavour"),
        create_ingredient_item("Artificial Vanilla Flavour"),
    ],
    
    "britannia-marie": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Sodium Metabisulphite"),
    ],
    
    # SNACKS & CHIPS
    "lays-classic": [
        create_ingredient_item("Potato"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
    ],
    
    "lays-cream-onion": [
        create_ingredient_item("Potato"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Onion Powder"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Citric Acid"),
    ],
    
    "lays-magic-masala": [
        create_ingredient_item("Potato"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Silicon Dioxide"),
    ],
    
    "kurkure-masala": [
        create_ingredient_item("Corn Meal"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Rice Meal"),
        create_ingredient_item("Gram Meal"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Silicon Dioxide"),
    ],
    
    "haldiram-bhujia": [
        create_ingredient_item("Gram Flour"),
        create_ingredient_item("Potato Flakes"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Moth Flour"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Red Chilli Powder"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Clove"),
        create_ingredient_item("Asafoetida"),
    ],
    
    "pringles": [
        create_ingredient_item("Dried Potatoes"),
        create_ingredient_item("Corn Oil"),
        create_ingredient_item("Cottonseed Oil"),
        create_ingredient_item("Soybean Oil"),
        create_ingredient_item("Corn Flour"),
        create_ingredient_item("Cornstarch"),
        create_ingredient_item("Rice Flour"),
        create_ingredient_item("Maltodextrin"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Wheat Starch"),
    ],
    
    "cheetos": [
        create_ingredient_item("Corn Meal"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Cheese Powder"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Allura Red"),
    ],
    
    # INSTANT NOODLES
    "maggi-masala": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Wheat Gluten"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Sodium Carbonate"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Potassium Carbonate"),
        create_ingredient_item("Mixed Spices"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Starch"),
        create_ingredient_item("Caramel Colour"),
        create_ingredient_item("Hydrolysed Groundnut Protein"),
        create_ingredient_item("Garlic Powder"),
        create_ingredient_item("Onion Powder"),
    ],
    
    # CHOCOLATES
    "cadbury-dairy-milk": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Ammonium Phosphatides"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Artificial Flavours"),
    ],
    
    # HEALTH DRINKS
    "horlicks": [
        create_ingredient_item("Malted Barley"),
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Protein Isolate"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Caramel Colour"),
    ],
    
    "bournvita": [
        create_ingredient_item("Malt Extract"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Caramel Colour"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Salt"),
    ],
    
    # SOFT DRINKS
    "coca-cola": [
        create_ingredient_item("Carbonated Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Phosphoric Acid"),
        create_ingredient_item("Caffeine"),
        create_ingredient_item("Natural Flavours"),
        create_ingredient_item("Caramel Colour"),
    ],
    
    "pepsi": [
        create_ingredient_item("Carbonated Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Caramel Colour"),
        create_ingredient_item("Phosphoric Acid"),
        create_ingredient_item("Caffeine"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Natural Flavours"),
    ],
    
    "thums-up": [
        create_ingredient_item("Carbonated Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Caramel Colour"),
        create_ingredient_item("Phosphoric Acid"),
        create_ingredient_item("Caffeine"),
        create_ingredient_item("Natural Flavours"),
    ],
    
    "sprite": [
        create_ingredient_item("Carbonated Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Natural Lemon Flavour"),
        create_ingredient_item("Natural Lime Flavour"),
        create_ingredient_item("Sodium Citrate"),
    ],
    
    "fanta-orange": [
        create_ingredient_item("Carbonated Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Natural Orange Flavour"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Sunset Yellow"),
    ],
    
    "tropicana": [
        create_ingredient_item("Orange Juice"),
    ],
    
    # DAIRY
    "amul-butter": [
        create_ingredient_item("Milk Fat"),
        create_ingredient_item("Salt"),
    ],
    
    # PERSONAL CARE - SOAPS
    "dove-soap": [
        create_ingredient_item("Sodium Lauroyl Isethionate"),
        create_ingredient_item("Stearic Acid"),
        create_ingredient_item("Sodium Tallowate"),
        create_ingredient_item("Sodium Palmitate"),
        create_ingredient_item("Lauric Acid"),
        create_ingredient_item("Sodium Isethionate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Stearate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Cocoate"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Tetrasodium Etidronate"),
        create_ingredient_item("Titanium Dioxide"),
    ],
    
    "pears-soap": [
        create_ingredient_item("Sodium Palmate"),
        create_ingredient_item("Sodium Cocoate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Propylene Glycol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Tetrasodium Etidronate"),
        create_ingredient_item("Orange Dye"),
        create_ingredient_item("Yellow Dye"),
    ],
    
    "lifebuoy-soap": [
        create_ingredient_item("Sodium Palmate"),
        create_ingredient_item("Sodium Palm Kernelate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Talc"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Thymol"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Titanium Dioxide"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Tetrasodium Etidronate"),
        create_ingredient_item("Orange Dye"),
        create_ingredient_item("Blue Dye"),
    ],
    
    # SHAMPOOS
    "clinic-plus": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Dimethiconol"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Guar Hydroxypropyltrimonium Chloride"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Milk Protein"),
        create_ingredient_item("Methylchloroisothiazolinone"),
        create_ingredient_item("Methylisothiazolinone"),
    ],
    
    "pantene-shampoo": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Sodium Citrate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Xylenesulfonate"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Stearyl Alcohol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Cetyl Alcohol"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Panthenol"),
        create_ingredient_item("Methylchloroisothiazolinone"),
        create_ingredient_item("Methylisothiazolinone"),
    ],
    
    # TOOTHPASTE
    "colgate-total": [
        create_ingredient_item("Water"),
        create_ingredient_item("Hydrated Silica"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("PVM/MA Copolymer"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Flavour"),
        create_ingredient_item("Cellulose Gum"),
        create_ingredient_item("Sodium Hydroxide"),
        create_ingredient_item("Carrageenan"),
        create_ingredient_item("Propylene Glycol"),
        create_ingredient_item("Sodium Fluoride"),
        create_ingredient_item("Triclosan"),
        create_ingredient_item("Sodium Saccharin"),
        create_ingredient_item("Titanium Dioxide"),
    ],
    
    "pepsodent": [
        create_ingredient_item("Calcium Carbonate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("Hydrated Silica"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Flavour"),
        create_ingredient_item("Cellulose Gum"),
        create_ingredient_item("Sodium Silicate"),
        create_ingredient_item("Sodium Monofluorophosphate"),
        create_ingredient_item("Sodium Saccharin"),
        create_ingredient_item("Titanium Dioxide"),
    ],
    
    # REMAINING BISCUITS & COOKIES
    "parle-monaco": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Sodium Metabisulphite"),
    ],
    
    "britannia-bourbon": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Artificial Chocolate Flavour"),
        create_ingredient_item("Artificial Vanilla Flavour"),
    ],
    
    "sunfeast-dark-fantasy": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Artificial Flavours"),
    ],
    
    "oreo": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Artificial Vanilla Flavour"),
    ],
    
    "parle-hide-seek": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Chocolate Chips"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Artificial Flavours"),
    ],
    
    "britannia-nutrichoice": [
        create_ingredient_item("Whole Wheat Flour"),
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Oats"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Sodium Metabisulphite"),
    ],
    
    "sunfeast-moms-magic": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Butter"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Artificial Butter Flavour"),
    ],
    
    "parle-krackjack": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Soy Lecithin"),
    ],
    
    "britannia-50-50": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Artificial Flavours"),
    ],
    
    "sunfeast-glucose": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
    ],
    
    "parle-20-20": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Artificial Butter Flavour"),
        create_ingredient_item("Artificial Vanilla Flavour"),
    ],
    
    "britannia-treat": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Invert Sugar Syrup"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Artificial Flavours"),
    ],
    
    # REMAINING SNACKS & CHIPS
    "kurkure-solid": [
        create_ingredient_item("Corn Meal"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Rice Meal"),
        create_ingredient_item("Gram Meal"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Tomato Powder"),
        create_ingredient_item("Onion Powder"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Citric Acid"),
    ],
    
    "bingo-mad-angles": [
        create_ingredient_item("Corn Meal"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Rice Meal"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Silicon Dioxide"),
    ],
    
    "haldiram-moong-dal": [
        create_ingredient_item("Moong Dal"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Red Chilli Powder"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Asafoetida"),
    ],
    
    "haldiram-sev": [
        create_ingredient_item("Gram Flour"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Moth Flour"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Red Chilli Powder"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Clove"),
        create_ingredient_item("Asafoetida"),
    ],
    
    "bikano-bhujia": [
        create_ingredient_item("Gram Flour"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Moth Flour"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Red Chilli Powder"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Asafoetida"),
    ],
    
    "bikano-aloo-lachha": [
        create_ingredient_item("Potato Flakes"),
        create_ingredient_item("Gram Flour"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Red Chilli Powder"),
        create_ingredient_item("Black Pepper"),
    ],
    
    "uncle-chipps": [
        create_ingredient_item("Potato"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Citric Acid"),
    ],
    
    "balaji-wafers": [
        create_ingredient_item("Potato"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Citric Acid"),
    ],
    
    "too-yumm": [
        create_ingredient_item("Corn Meal"),
        create_ingredient_item("Rice Bran Oil"),
        create_ingredient_item("Potato Starch"),
        create_ingredient_item("Beetroot Powder"),
        create_ingredient_item("Spinach Powder"),
        create_ingredient_item("Tomato Powder"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
    ],
    
    "act-ii-popcorn": [
        create_ingredient_item("Popcorn"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Butter Flavour"),
        create_ingredient_item("Beta Carotene"),
    ],
    
    "cornitos": [
        create_ingredient_item("Corn"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Lime"),
    ],
    
    "doritos": [
        create_ingredient_item("Corn"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Cheese Powder"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Citric Acid"),
    ],
    
    "bingo-salted": [
        create_ingredient_item("Potato"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
    ],
    
    # REMAINING INSTANT NOODLES
    "maggi-atta": [
        create_ingredient_item("Whole Wheat Flour"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Wheat Gluten"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Sodium Carbonate"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Potassium Carbonate"),
        create_ingredient_item("Mixed Spices"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Starch"),
    ],
    
    "top-ramen": [
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Sodium Carbonate"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Potassium Carbonate"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Starch"),
        create_ingredient_item("Hydrolysed Vegetable Protein"),
        create_ingredient_item("Curry Powder"),
    ],
    
    "yippee": [
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Sodium Carbonate"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Potassium Carbonate"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Starch"),
        create_ingredient_item("Citric Acid"),
    ],
    
    "sunfeast-yippee-atta": [
        create_ingredient_item("Whole Wheat Flour"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Sodium Carbonate"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Potassium Carbonate"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Starch"),
    ],
    
    "knorr-soupy": [
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Sodium Carbonate"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Potassium Carbonate"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Starch"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Vegetable Powder"),
    ],
    
    "wai-wai": [
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Sodium Carbonate"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Potassium Carbonate"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Disodium Guanylate"),
        create_ingredient_item("Disodium Inosinate"),
        create_ingredient_item("Starch"),
    ],
    
    "patanjali-atta-noodles": [
        create_ingredient_item("Whole Wheat Flour"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Sodium Bicarbonate"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Starch"),
    ],
    
    # REMAINING CHOCOLATES & CONFECTIONERY
    "cadbury-silk": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Ammonium Phosphatides"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Artificial Flavours"),
    ],
    
    "kitkat": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Vegetable Fat"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Natural Vanilla Flavour"),
    ],
    
    "nestle-munch": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Peanuts"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Vegetable Fat"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Flavours"),
    ],
    
    "amul-dark-chocolate": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Vanilla Flavour"),
    ],
    
    "amul-milk-chocolate": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Vanilla Flavour"),
    ],
    
    "5-star": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Peanuts"),
        create_ingredient_item("Vegetable Fat"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Flavours"),
    ],
    
    "perk": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Vegetable Fat"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Flavours"),
    ],
    
    "snickers": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Mass"),
        create_ingredient_item("Skimmed Milk Powder"),
        create_ingredient_item("Milk Fat"),
        create_ingredient_item("Lactose"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Peanuts"),
        create_ingredient_item("Glucose Syrup"),
        create_ingredient_item("Palm Fat"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Egg White"),
        create_ingredient_item("Flavour"),
    ],
    
    "mars": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Glucose Syrup"),
        create_ingredient_item("Milk Powder"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Mass"),
        create_ingredient_item("Sunflower Oil"),
        create_ingredient_item("Milk Fat"),
        create_ingredient_item("Lactose"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Egg White"),
        create_ingredient_item("Flavour"),
    ],
    
    "ferrero-rocher": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Mass"),
        create_ingredient_item("Skimmed Milk Powder"),
        create_ingredient_item("Milk Fat"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Hazelnuts"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Whey Powder"),
        create_ingredient_item("Fat-Reduced Cocoa"),
        create_ingredient_item("Ammonium Bicarbonate"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Flavour"),
    ],
    
    "cadbury-bournville": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Ammonium Phosphatides"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Flavours"),
    ],
    
    "nestle-milkybar": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Natural Vanilla Flavour"),
    ],
    
    "cadbury-gems": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Butter"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Ammonium Phosphatides"),
        create_ingredient_item("Polyglycerol Polyricinoleate"),
        create_ingredient_item("Tartrazine"),
        create_ingredient_item("Sunset Yellow"),
        create_ingredient_item("Carmoisine"),
        create_ingredient_item("Ponceau 4R"),
        create_ingredient_item("Brilliant Blue"),
        create_ingredient_item("Shellac"),
        create_ingredient_item("Flavours"),
    ],
    
    "cadbury-eclairs": [
        create_ingredient_item("Glucose Syrup"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Vegetable Fat"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Flavours"),
    ],
    
    # REMAINING HEALTH DRINKS
    "complan": [
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Maltodextrin"),
        create_ingredient_item("Vegetable Oil"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Flavours"),
    ],
    
    "boost": [
        create_ingredient_item("Malt Extract"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Caramel Colour"),
        create_ingredient_item("Salt"),
    ],
    
    "pediasure": [
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Maltodextrin"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Vegetable Oil"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Vanilla Flavour"),
    ],
    
    "protinex": [
        create_ingredient_item("Milk Protein"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Maltodextrin"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Flavours"),
    ],
    
    "milo": [
        create_ingredient_item("Malt Extract"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Salt"),
    ],
    
    "patanjali-nutrela": [
        create_ingredient_item("Almond Powder"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cardamom Powder"),
        create_ingredient_item("Saffron"),
    ],
    
    "nestle-ceregrow": [
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Soy Lecithin"),
    ],
    
    "junior-horlicks": [
        create_ingredient_item("Malted Barley"),
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Caramel Colour"),
    ],
    
    # REMAINING BEVERAGES
    "fanta": [
        create_ingredient_item("Carbonated Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Natural Orange Flavour"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Sunset Yellow"),
    ],
    
    "limca": [
        create_ingredient_item("Carbonated Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Natural Lemon Flavour"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    
    "maaza": [
        create_ingredient_item("Water"),
        create_ingredient_item("Mango Pulp"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Vitamin C"),
        create_ingredient_item("Natural Mango Flavour"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Sunset Yellow"),
    ],
    
    "frooti": [
        create_ingredient_item("Water"),
        create_ingredient_item("Mango Pulp"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Vitamin C"),
        create_ingredient_item("Natural Mango Flavour"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    
    "real-juice": [
        create_ingredient_item("Water"),
        create_ingredient_item("Orange Juice Concentrate"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Vitamin C"),
        create_ingredient_item("Natural Orange Flavour"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    
    # REMAINING DAIRY PRODUCTS
    "amul-cheese-slices": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Cheese Culture"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Phosphate"),
        create_ingredient_item("Nisin"),
    ],
    
    "amul-cheese-spread": [
        create_ingredient_item("Cheese"),
        create_ingredient_item("Milk"),
        create_ingredient_item("Cheese Culture"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Water"),
        create_ingredient_item("Butter"),
        create_ingredient_item("Sodium Phosphate"),
        create_ingredient_item("Sodium Polyphosphate"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Nisin"),
    ],
    
    "mother-dairy-dahi": [
        create_ingredient_item("Toned Milk"),
        create_ingredient_item("Lactic Acid Culture"),
    ],
    
    "amul-lassi": [
        create_ingredient_item("Toned Milk"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Lactic Acid Culture"),
        create_ingredient_item("Cardamom"),
    ],
    
    "britannia-cheese": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Cheese Culture"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Phosphate"),
        create_ingredient_item("Nisin"),
    ],
    
    "nestle-milkmaid": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Sugar"),
    ],
    
    "amul-paneer": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Citric Acid"),
    ],
    
    "mother-dairy-paneer": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Citric Acid"),
    ],
    
    "amul-shrikhand": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Lactic Acid Culture"),
        create_ingredient_item("Cardamom"),
        create_ingredient_item("Saffron"),
        create_ingredient_item("Nutmeg"),
    ],
    
    # REMAINING PERSONAL CARE - SOAPS
    "dettol-soap": [
        create_ingredient_item("Sodium Palmate"),
        create_ingredient_item("Sodium Palm Kernelate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Chloroxylenol"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Titanium Dioxide"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Tetrasodium Etidronate"),
        create_ingredient_item("Orange Dye"),
    ],
    
    "lux-soap": [
        create_ingredient_item("Sodium Palmate"),
        create_ingredient_item("Sodium Palm Kernelate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Titanium Dioxide"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Tetrasodium Etidronate"),
        create_ingredient_item("Red Dye"),
    ],
    
    "santoor-soap": [
        create_ingredient_item("Sodium Palmate"),
        create_ingredient_item("Sodium Palm Kernelate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sandalwood Oil"),
        create_ingredient_item("Turmeric Extract"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Titanium Dioxide"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Yellow Dye"),
    ],
    
    "patanjali-neem-soap": [
        create_ingredient_item("Soap Noodles"),
        create_ingredient_item("Neem Oil"),
        create_ingredient_item("Neem Leaves Extract"),
        create_ingredient_item("Tulsi Extract"),
        create_ingredient_item("Aloe Vera Extract"),
        create_ingredient_item("Turmeric Extract"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Perfume"),
    ],
    
    "patanjali-haldi-soap": [
        create_ingredient_item("Soap Noodles"),
        create_ingredient_item("Turmeric Extract"),
        create_ingredient_item("Sandalwood Oil"),
        create_ingredient_item("Aloe Vera Extract"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Perfume"),
    ],
    
    "himalaya-neem-soap": [
        create_ingredient_item("Sodium Palmate"),
        create_ingredient_item("Sodium Palm Kernelate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Neem Extract"),
        create_ingredient_item("Turmeric Extract"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Titanium Dioxide"),
        create_ingredient_item("Tetrasodium EDTA"),
    ],
    
    "medimix-soap": [
        create_ingredient_item("Soap Noodles"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Turmeric Extract"),
        create_ingredient_item("Neem Extract"),
        create_ingredient_item("Aloe Vera Extract"),
        create_ingredient_item("Sandalwood Extract"),
        create_ingredient_item("Herbal Extracts"),
        create_ingredient_item("Perfume"),
    ],
    
    "cinthol-soap": [
        create_ingredient_item("Sodium Palmate"),
        create_ingredient_item("Sodium Palm Kernelate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Titanium Dioxide"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Blue Dye"),
    ],
    
    "fiama-gel-bar": [
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Preservatives"),
    ],
    
    # REMAINING SHAMPOOS
    "head-shoulders": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Zinc Pyrithione"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Glycol Distearate"),
        create_ingredient_item("Dimethiconol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Guar Hydroxypropyltrimonium Chloride"),
        create_ingredient_item("Tetrasodium EDTA"),
        create_ingredient_item("Methylchloroisothiazolinone"),
        create_ingredient_item("Methylisothiazolinone"),
    ],
    
    "sunsilk": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Dimethiconol"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Carbomer"),
        create_ingredient_item("Guar Hydroxypropyltrimonium Chloride"),
        create_ingredient_item("TEA-Dodecylbenzenesulfonate"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Disodium EDTA"),
        create_ingredient_item("Methylchloroisothiazolinone"),
        create_ingredient_item("Methylisothiazolinone"),
    ],
    
    "dove-shampoo": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Dimethiconol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Guar Hydroxypropyltrimonium Chloride"),
        create_ingredient_item("TEA-Dodecylbenzenesulfonate"),
        create_ingredient_item("Disodium EDTA"),
        create_ingredient_item("Methylchloroisothiazolinone"),
        create_ingredient_item("Methylisothiazolinone"),
    ],
    
    "himalaya-shampoo": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Tea Tree Oil"),
        create_ingredient_item("Rosemary Extract"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Fragrance"),
    ],
    
    "patanjali-shampoo": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Aloe Vera Extract"),
        create_ingredient_item("Bhringraj Extract"),
        create_ingredient_item("Amla Extract"),
        create_ingredient_item("Neem Extract"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    
    "tresemme": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Dimethiconol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Carbomer"),
        create_ingredient_item("Guar Hydroxypropyltrimonium Chloride"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Hydrolyzed Keratin"),
        create_ingredient_item("Disodium EDTA"),
        create_ingredient_item("Methylchloroisothiazolinone"),
        create_ingredient_item("Methylisothiazolinone"),
    ],
    
    "loreal-shampoo": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Dimethiconol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Carbomer"),
        create_ingredient_item("Guar Hydroxypropyltrimonium Chloride"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Ceramide"),
        create_ingredient_item("Disodium EDTA"),
        create_ingredient_item("Methylchloroisothiazolinone"),
        create_ingredient_item("Methylisothiazolinone"),
    ],
    
    "garnier-shampoo": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Dimethiconol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Fruit Extract"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Guar Hydroxypropyltrimonium Chloride"),
        create_ingredient_item("Disodium EDTA"),
        create_ingredient_item("Methylchloroisothiazolinone"),
        create_ingredient_item("Methylisothiazolinone"),
    ],
    
    # REMAINING TOOTHPASTE
    "colgate-visible-white": [
        create_ingredient_item("Water"),
        create_ingredient_item("Hydrated Silica"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Flavour"),
        create_ingredient_item("Cellulose Gum"),
        create_ingredient_item("Sodium Hydroxide"),
        create_ingredient_item("Carrageenan"),
        create_ingredient_item("Sodium Fluoride"),
        create_ingredient_item("Sodium Saccharin"),
        create_ingredient_item("Titanium Dioxide"),
    ],
    
    "sensodyne": [
        create_ingredient_item("Water"),
        create_ingredient_item("Hydrated Silica"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("Potassium Nitrate"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Flavour"),
        create_ingredient_item("Cellulose Gum"),
        create_ingredient_item("Sodium Hydroxide"),
        create_ingredient_item("Sodium Fluoride"),
        create_ingredient_item("Sodium Saccharin"),
        create_ingredient_item("Titanium Dioxide"),
    ],
    
    "patanjali-dant-kanti": [
        create_ingredient_item("Calcium Carbonate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("Neem Extract"),
        create_ingredient_item("Clove Oil"),
        create_ingredient_item("Mint Extract"),
        create_ingredient_item("Babool Extract"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Cellulose Gum"),
        create_ingredient_item("Sodium Saccharin"),
    ],
    
    "dabur-red": [
        create_ingredient_item("Calcium Carbonate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("Clove Oil"),
        create_ingredient_item("Mint Extract"),
        create_ingredient_item("Camphor"),
        create_ingredient_item("Tomar Seed Extract"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Cellulose Gum"),
        create_ingredient_item("Sodium Saccharin"),
    ],
    
    "himalaya-toothpaste": [
        create_ingredient_item("Calcium Carbonate"),
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("Neem Extract"),
        create_ingredient_item("Pomegranate Extract"),
        create_ingredient_item("Miswak Extract"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Cellulose Gum"),
        create_ingredient_item("Sodium Saccharin"),
    ],
    
    "close-up": [
        create_ingredient_item("Water"),
        create_ingredient_item("Hydrated Silica"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sorbitol"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Flavour"),
        create_ingredient_item("Cellulose Gum"),
        create_ingredient_item("Sodium Hydroxide"),
        create_ingredient_item("Sodium Fluoride"),
        create_ingredient_item("Sodium Saccharin"),
        create_ingredient_item("Red Dye"),
        create_ingredient_item("Titanium Dioxide"),
    ],
}

# For products not in FULL_INGREDIENTS, use generic ingredient list
DEFAULT_INGREDIENTS = [
    create_ingredient_item("Standard Food/Cosmetic Ingredients")
]

def get_ingredients(product_key):
    """Get full ingredient list for a product"""
    return FULL_INGREDIENTS.get(product_key, DEFAULT_INGREDIENTS)