"""Script to add comprehensive ingredient database entries to ingredient_database.py"""
import re, sys

with open('backend/routes/ingredient_database.py', encoding='utf-8') as f:
    src = f.read()

print(f"Original: {src.count(chr(10))} lines")

# ── STEP 1: Add to INGREDIENT_DESCRIPTIONS ────────────────────────────────────
desc_end_marker = "\n}\n\n\n# Ingredients that are commonly_questioned"
pos_desc_end = src.find(desc_end_marker)
if pos_desc_end == -1:
    print("ERROR: Cannot find end of INGREDIENT_DESCRIPTIONS")
    sys.exit(1)

new_entries = r"""
    # ══ Food Additive E Numbers / INS Numbers (comprehensive) ══════════════════

    # ── Colours ──────────────────────────────────────────────────────────────
    'curcumin': 'Curcumin (E100/INS 100) is the natural yellow pigment from turmeric. Safe and anti-inflammatory. FSSAI, EU and Codex approved.',
    'e100': 'E100 is the EU/INS code for Curcumin. Natural turmeric yellow food colour. Safe and beneficial.',
    'annatto': 'Annatto (E160b/INS 160b) is a natural orange-yellow pigment from achiote seeds, used in cheeses, margarine and snacks. Safe; rare allergy in aspirin-sensitive individuals.',
    'e160b': 'E160b is the EU/INS code for Annatto (Bixin/Norbixin). Natural orange-red colour. Safe.',
    'paprika extract': 'Paprika Extract (E160c/INS 160c) is a natural red-orange carotenoid from red capsicum peppers. Safe.',
    'e160c': 'E160c is the EU/INS code for Paprika Extract. Natural red-orange colour from capsicum. Safe.',
    'lycopene': 'Lycopene (E160d/INS 160d) is the natural red carotenoid from tomatoes with antioxidant benefits. Safe.',
    'e160d': 'E160d is the EU/INS code for Lycopene. Natural red colour from tomatoes. Safe.',
    'lutein': 'Lutein (E161b/INS 161b) is a natural yellow carotenoid from marigold flowers. Associated with eye health. Safe.',
    'e161b': 'E161b is the EU/INS code for Lutein. Natural yellow colour with eye health benefits. Safe.',
    'beetroot red': 'Beetroot Red / Betanin (E162/INS 162) is the natural red-purple pigment from red beetroot. Safe; harmless pink urine (beeturia) possible.',
    'betanin': 'Betanin (E162/INS 162) is the red pigment from beetroot used as a natural food colour. Safe.',
    'e162': 'E162 is the EU/INS code for Beetroot Red (Betanin). Natural red-purple colour. Safe.',
    'anthocyanins': 'Anthocyanins (E163/INS 163) are natural red-purple-blue pigments from berries, grapes and red cabbage. Rich in antioxidants. Safe.',
    'e163': 'E163 is the EU/INS code for Anthocyanins. Natural plant pigments from berries. Safe.',
    'calcium carbonate food': 'Calcium Carbonate (E170/INS 170) is used as a white food colour, anti-caking agent and calcium supplement. Safe and nutritionally beneficial.',
    'e170': 'E170 is the EU/INS code for Calcium Carbonate. White colour and calcium supplement. Safe.',
    'iron oxides': 'Iron Oxides (E172/INS 172) are mineral pigments producing red, yellow, brown and black food colours. Safe at approved levels.',
    'e172': 'E172 is the EU/INS code for Iron Oxides and Hydroxides. Mineral food colours. Safe at approved levels.',
    'e174': 'E174 is the EU code for Silver. Metallic surface decoration on confectionery. Chemically inert; safe in decorative amounts.',
    'e175': 'E175 is the EU code for Gold. Metallic food decoration. Chemically inert; safe.',
    'e140': 'E140 is the EU/INS code for Chlorophylls. Natural green plant pigments. Safe.',
    'e141': 'E141 is the EU/INS code for Copper Complexes of Chlorophylls. Stabilised natural green colours. Safe at permitted levels.',
    'e150a': 'E150a is Plain Caramel (Class I). Produced without ammonia or sulphites. Used in spirits. Safest caramel class.',
    'e150b': 'E150b is Caustic Sulphite Caramel (Class II). Used in cognac and sherry. Safe.',
    'e150c': 'E150c is Ammonia Caramel (Class III). Used in beer and sauces. Safe at typical food levels.',

    # ── Acidity regulators ─────────────────────────────────────────────────
    'acetic acid': 'Acetic Acid (E260/INS 260) is the acid in vinegar. Naturally produced by fermentation. Safe acidity regulator and preservative in pickles, sauces and condiments.',
    'e260': 'E260 is the EU/INS code for Acetic Acid (vinegar acid). Safe acidity regulator.',
    'potassium acetate': 'Potassium Acetate (E261/INS 261) is the potassium salt of acetic acid. Acidity regulator and low-sodium salt substitute. Safe.',
    'e261': 'E261 is the EU/INS code for Potassium Acetate. Acidity regulator and salt substitute. Safe.',
    'sodium acetate': 'Sodium Acetate (E262/INS 262) is the sodium salt of acetic acid. Acidity regulator; gives salt-and-vinegar crisps their flavour. Safe.',
    'e262': 'E262 is the EU/INS code for Sodium Acetates. Acidity regulator. Safe.',
    'e270': 'E270 is the EU/INS code for Lactic Acid. Natural fermentation acid found in yoghurt and pickles. Safe.',
    'propionic acid': 'Propionic Acid (E280/INS 280) is a short-chain fatty acid naturally in Swiss cheese. Used as a mould inhibitor in bread. Safe -- metabolised as a normal fatty acid.',
    'e280': 'E280 is the EU/INS code for Propionic Acid. Natural mould inhibitor in bread. Safe.',
    'sodium propionate': 'Sodium Propionate (E281/INS 281) is the sodium salt of propionic acid. Mould inhibitor in bakery products. Safe.',
    'e281': 'E281 is the EU/INS code for Sodium Propionate. Mould inhibitor in baked goods. Safe.',
    'calcium propionate': 'Calcium Propionate (E282/INS 282) is the most widely used bread preservative. Inhibits mould and adds dietary calcium. Safe.',
    'e282': 'E282 is the EU/INS code for Calcium Propionate. Most widely used bread mould inhibitor; adds calcium. Safe.',
    'potassium propionate': 'Potassium Propionate (E283/INS 283) is the potassium salt of propionic acid. Mould inhibitor in baked goods. Safe.',
    'e283': 'E283 is the EU/INS code for Potassium Propionate. Mould inhibitor in baked goods. Safe.',
    'e290': 'E290 is the EU/INS code for Carbon Dioxide. Used to carbonate drinks and preserve freshness. Safe -- the gas we exhale.',
    'malic acid': 'Malic Acid (E296/INS 296) is the natural tart acid from apples and grapes. Used as an acidity regulator in beverages and confectionery. Safe.',
    'e296': 'E296 is the EU/INS code for Malic Acid. Natural apple acid; acidity regulator. Safe.',
    'fumaric acid': 'Fumaric Acid (E297/INS 297) is a naturally occurring acid from the Krebs cycle. Used as an acidity regulator and raising acid. Safe.',
    'e297': 'E297 is the EU/INS code for Fumaric Acid. Natural acidity regulator. Safe.',

    # ── Antioxidants (E300-E329) ─────────────────────────────────────────
    'e300': 'E300 is the EU/INS code for Ascorbic Acid (Vitamin C). Essential vitamin and food antioxidant. Safe and nutritionally beneficial.',
    'sodium ascorbate': 'Sodium Ascorbate (E301/INS 301) is a non-acidic form of Vitamin C. Antioxidant in processed meats and beverages. Safe.',
    'e301': 'E301 is the EU/INS code for Sodium Ascorbate. Non-acidic Vitamin C antioxidant. Safe.',
    'calcium ascorbate': 'Calcium Ascorbate (E302/INS 302) is the calcium salt of Vitamin C. Antioxidant and calcium supplement. Safe.',
    'e302': 'E302 is the EU/INS code for Calcium Ascorbate. Vitamin C and calcium supplement. Safe.',
    'ascorbyl palmitate': 'Ascorbyl Palmitate (E304/INS 304) is a fat-soluble Vitamin C ester. Antioxidant in oils and fats. Safe.',
    'e304': 'E304 is the EU/INS code for Ascorbyl Palmitate. Fat-soluble Vitamin C antioxidant. Safe.',
    'e306': 'E306 is the EU/INS code for Tocopherol-rich extract (Vitamin E). Natural antioxidant. Safe and nutritionally beneficial.',
    'e307': 'E307 is the EU/INS code for Alpha-Tocopherol (most active Vitamin E form). Safe.',
    'e308': 'E308 is the EU/INS code for Gamma-Tocopherol (Vitamin E form). Safe.',
    'e309': 'E309 is the EU/INS code for Delta-Tocopherol (Vitamin E form). Safe.',
    'propyl gallate': 'Propyl Gallate (E310/INS 310) is a synthetic antioxidant in fats and oils. Associated with tumour promotion in animal studies; banned in baby foods in the EU; under EFSA review. Approved with quantity limits for general food use.',
    'e310': 'E310 is the EU/INS code for Propyl Gallate. Synthetic antioxidant under regulatory review; banned in baby foods in EU.',
    'octyl gallate': 'Octyl Gallate (E311/INS 311) is a synthetic gallate antioxidant in edible fats. Approved with quantity limits.',
    'e311': 'E311 is the EU/INS code for Octyl Gallate. Synthetic antioxidant. Approved with limits.',
    'dodecyl gallate': 'Dodecyl Gallate (E312/INS 312) is a synthetic gallate antioxidant in edible fats. Approved with quantity limits.',
    'e312': 'E312 is the EU/INS code for Dodecyl Gallate. Synthetic antioxidant. Approved with limits.',
    'sodium lactate': 'Sodium Lactate (E325/INS 325) is the sodium salt of lactic acid. Humectant and low-sodium salt substitute. Safe.',
    'e325': 'E325 is the EU/INS code for Sodium Lactate. Humectant and salt substitute. Safe.',
    'potassium lactate': 'Potassium Lactate (E326/INS 326) is the potassium salt of lactic acid. Antimicrobial in processed meats. Safe.',
    'e326': 'E326 is the EU/INS code for Potassium Lactate. Antimicrobial in processed meats. Safe.',
    'calcium lactate': 'Calcium Lactate (E327/INS 327) is the calcium salt of lactic acid. Firming agent and calcium supplement. Safe.',
    'e327': 'E327 is the EU/INS code for Calcium Lactate. Firming agent and calcium source. Safe.',
    'tartaric acid': 'Tartaric Acid (E334/INS 334) is the natural acid from grapes, responsible for wine tartness. Used as an acidity regulator in baked goods and confectionery. Safe.',
    'e334': 'E334 is the EU/INS code for Tartaric Acid. Natural grape acid. Safe.',
    'e335': 'E335 is the EU/INS code for Sodium Tartrates. Acidity regulators. Safe.',
    'e336': 'E336 is the EU/INS code for Potassium Tartrates (Cream of Tartar). Classic baking ingredient. Safe.',
    'e337': 'E337 is the EU/INS code for Sodium Potassium Tartrate (Rochelle Salt). Acidity regulator. Safe.',
    'e340': 'E340 is the EU/INS code for Potassium Phosphates. Acidity regulators. Safe at approved levels.',
    'calcium phosphate': 'Calcium Phosphates (E341/INS 341) are used as raising agents and calcium supplements in baked goods and fortified foods. Safe.',
    'e341': 'E341 is the EU/INS code for Calcium Phosphates. Raising agents and calcium supplements. Safe.',
    'adipic acid': 'Adipic Acid (E355/INS 355) is an organic dicarboxylic acid used as an acidity regulator and raising acid. Safe.',
    'e355': 'E355 is the EU/INS code for Adipic Acid. Acidity regulator and raising acid. Safe.',
    'succinic acid': 'Succinic Acid (E363/INS 363) is a naturally occurring acid from fermentation. Acidity regulator. Safe.',
    'e363': 'E363 is the EU/INS code for Succinic Acid. Natural acidity regulator. Safe.',
    'gluconic acid': 'Gluconic Acid (E574/INS 574) is a natural acid from fermentation found in honey and wine. Safe.',
    'e574': 'E574 is the EU/INS code for Gluconic Acid. Natural fermentation acid. Safe.',
    'glucono delta-lactone': 'Glucono Delta-Lactone (GDL/E575/INS 575) is a natural mild acidifier used in tofu, cheese and baked goods. Safe.',
    'e575': 'E575 is the EU/INS code for Glucono Delta-Lactone (GDL). Natural mild acidifier. Safe.',
    'sodium gluconate': 'Sodium Gluconate (E576/INS 576) is the sodium salt of gluconic acid. Sequestrant and acidity regulator. Safe.',
    'e576': 'E576 is the EU/INS code for Sodium Gluconate. Sequestrant. Safe.',
    'potassium gluconate': 'Potassium Gluconate (E577/INS 577) is the potassium salt of gluconic acid. Potassium supplement. Safe.',
    'e577': 'E577 is the EU/INS code for Potassium Gluconate. Potassium supplement. Safe.',
    'calcium gluconate': 'Calcium Gluconate (E578/INS 578) is the calcium salt of gluconic acid. Calcium supplement. Safe.',
    'e578': 'E578 is the EU/INS code for Calcium Gluconate. Calcium supplement. Safe.',
    'ferrous gluconate': 'Ferrous Gluconate (E579/INS 579) is used to colour black olives and as an iron supplement. Safe.',
    'e579': 'E579 is the EU/INS code for Ferrous Gluconate. Iron source and colour fixative. Safe.',

    # ── Emulsifiers / Hydrocolloids (E400-E499) ──────────────────────────
    'alginic acid': 'Alginic Acid (E400/INS 400) is a natural polysaccharide from brown seaweed. Thickener and gelling agent. Safe; dietary fibre.',
    'e400': 'E400 is the EU/INS code for Alginic Acid. Natural seaweed thickener. Safe.',
    'sodium alginate': 'Sodium Alginate (E401/INS 401) is the most widely used alginate from brown seaweed. Gelling agent in ice cream, salad dressings and molecular gastronomy. Safe; dietary fibre.',
    'e401': 'E401 is the EU/INS code for Sodium Alginate. Widely used seaweed gelling agent. Safe.',
    'potassium alginate': 'Potassium Alginate (E402/INS 402) is the potassium salt of alginic acid. Seaweed thickener. Safe.',
    'e402': 'E402 is the EU/INS code for Potassium Alginate. Seaweed thickener. Safe.',
    'e403': 'E403 is the EU/INS code for Ammonium Alginate. Seaweed thickener. Safe.',
    'calcium alginate': 'Calcium Alginate (E404/INS 404) forms thermo-irreversible gels from seaweed. Used in food and wound dressings. Safe.',
    'e404': 'E404 is the EU/INS code for Calcium Alginate. Natural seaweed gel-former. Safe.',
    'propylene glycol alginate': 'Propylene Glycol Alginate (E405/INS 405) is an acid-stable alginate ester used in salad dressings and beer foam. Safe at approved levels.',
    'e405': 'E405 is the EU/INS code for Propylene Glycol Alginate. Acid-stable seaweed gum. Safe.',
    'agar': 'Agar (E406/INS 406, Agar-Agar) is a natural polysaccharide from red algae. The vegetarian/vegan alternative to gelatin. Forms firm, clear gels. Safe; dietary fibre.',
    'e406': 'E406 is the EU/INS code for Agar (Agar-Agar). Natural red algae gelling agent. Vegetarian gelatin. Safe.',
    'locust bean gum': 'Locust Bean Gum (E410/INS 410, Carob Bean Gum) is a natural polysaccharide from carob seeds. Thickener in ice cream and dairy. Safe; dietary fibre.',
    'e410': 'E410 is the EU/INS code for Locust Bean Gum (Carob Gum). Natural seed thickener. Safe.',
    'tragacanth': 'Tragacanth (E413/INS 413) is a natural gum from Astragalus shrubs. One of the oldest food gums; used in confectionery. Safe.',
    'e413': 'E413 is the EU/INS code for Tragacanth. Natural plant gum thickener. Safe.',
    'gum arabic': 'Gum Arabic (E414/INS 414, Acacia Gum) is a natural gum from acacia trees of Africa. The world\'s most widely used food gum. Safe; prebiotic dietary fibre.',
    'acacia gum': 'Acacia Gum (E414/INS 414, Gum Arabic) from acacia trees is the world\'s most widely used food gum. Safe; prebiotic.',
    'e414': 'E414 is the EU/INS code for Gum Arabic (Acacia Gum). World\'s most used food gum. Safe.',
    'karaya gum': 'Karaya Gum (E416/INS 416) is a natural gum from Indian Sterculia trees. Thickener and stabiliser. Safe; rare sensitivity possible.',
    'e416': 'E416 is the EU/INS code for Karaya Gum. Indian plant gum. Safe.',
    'tara gum': 'Tara Gum (E417/INS 417) is a natural polysaccharide from tara plant seeds. Thickener. Safe.',
    'e417': 'E417 is the EU/INS code for Tara Gum. Natural seed gum. Safe.',
    'gellan gum': 'Gellan Gum (E418/INS 418) is a polysaccharide from bacterial fermentation. Gelling agent in plant-based milks and confectionery. Safe.',
    'e418': 'E418 is the EU/INS code for Gellan Gum. Microbial gelling agent. Safe.',
    'e420': 'E420 is the EU/INS code for Sorbitol. Sugar alcohol sweetener from fruits; laxative effects at >50g/day; label warning required.',
    'e421': 'E421 is the EU/INS code for Mannitol. Natural sugar alcohol; laxative effects; label warning required.',
    'e422': 'E422 is the EU/INS code for Glycerol (Glycerine). Natural humectant from fats. Safe.',
    'konjac': 'Konjac (E425/INS 425) is a polysaccharide from the konjac plant. Rich in glucomannan fibre with cholesterol-lowering benefits. EU restricts certain firm jelly formats for children due to choking risk.',
    'e425': 'E425 is the EU/INS code for Konjac (Konjac Gum). High-fibre gelling agent; EU restricts certain children\'s jelly formats.',
    'e440': 'E440 is the EU/INS code for Pectins. Natural gelling agent from citrus peel. Safe; soluble dietary fibre.',
    'e441': 'E441 is the EU/INS code for Gelatin. Animal-derived gelling protein. Not suitable for vegetarians, vegans or halal/kosher.',
    'ammonium phosphatides': 'Ammonium Phosphatides (E442/INS 442) are emulsifiers from vegetable oils used in chocolate to reduce viscosity. Safe.',
    'e442': 'E442 is the EU/INS code for Ammonium Phosphatides. Chocolate emulsifier. Safe.',
    'sucrose esters': 'Sucrose Esters of Fatty Acids (E473/INS 473) are emulsifiers from sucrose and fatty acids. Used in baked goods and dairy. Safe.',
    'e473': 'E473 is the EU/INS code for Sucrose Esters of Fatty Acids. Emulsifiers. Safe.',
    'e475': 'E475 is the EU/INS code for Polyglycerol Esters of Fatty Acids. Emulsifiers in confectionery. Safe.',
    'polysorbate 20': 'Polysorbate 20 (E432/INS 432) is a non-ionic emulsifier in food and cosmetics. Ethoxylation may introduce trace 1,4-dioxane (IARC Group 2B). Safe within approved limits.',
    'e432': 'E432 is the EU/INS code for Polysorbate 20. Non-ionic emulsifier; trace 1,4-dioxane possible from ethoxylation. Safe within limits.',
    'polysorbate 80': 'Polysorbate 80 (E433/INS 433) is a widely used non-ionic emulsifier in food, vaccines and cosmetics. Ethoxylation may introduce trace 1,4-dioxane. Safe within approved limits.',
    'e433': 'E433 is the EU/INS code for Polysorbate 80. Widely used emulsifier; trace 1,4-dioxane possible. Safe within limits.',
    'polysorbate 60': 'Polysorbate 60 (E435/INS 435) is a non-ionic emulsifier in baked goods and whipped toppings. Safe within approved limits.',
    'e435': 'E435 is the EU/INS code for Polysorbate 60. Emulsifier in baked goods. Safe within limits.',
    'polysorbate 65': 'Polysorbate 65 (E436/INS 436) is an emulsifier in ice cream and chocolate coatings. Safe within approved limits.',
    'e436': 'E436 is the EU/INS code for Polysorbate 65. Emulsifier. Safe within limits.',
    'e460': 'E460 is the EU/INS code for Microcrystalline Cellulose. Insoluble dietary fibre; anti-caking agent. Safe.',
    'e461': 'E461 is the EU/INS code for Methyl Cellulose. Heat-set modified cellulose in plant-based burgers. Safe.',
    'e464': 'E464 is the EU/INS code for Hydroxypropyl Methyl Cellulose (HPMC). Used in vegetarian capsules and gluten-free baking. Safe.',
    'datem': 'DATEM (E472e/INS 472e) is a highly effective bread dough emulsifier. Key ingredient in industrial baking. Safe.',
    'e472e': 'E472e is the EU/INS code for DATEM. Key bread dough emulsifier. Safe.',
    'sodium stearoyl lactylate': 'Sodium Stearoyl Lactylate (SSL/E481/INS 481) is a bread emulsifier that strengthens gluten and extends shelf life. Safe.',
    'e481': 'E481 is the EU/INS code for Sodium Stearoyl Lactylate (SSL). Key bread emulsifier. Safe.',
    'calcium stearoyl lactylate': 'Calcium Stearoyl Lactylate (CSL/E482/INS 482) is a bread emulsifier and dough conditioner. Safe.',
    'e482': 'E482 is the EU/INS code for Calcium Stearoyl Lactylate (CSL). Bread emulsifier. Safe.',
    'e491': 'E491 is the EU/INS code for Sorbitan Monostearate (Span 60). Emulsifier. Safe.',
    'e492': 'E492 is the EU/INS code for Sorbitan Tristearate. Emulsifier. Safe.',
    'e493': 'E493 is the EU/INS code for Sorbitan Monolaurate (Span 20). Emulsifier. Safe.',
    'e494': 'E494 is the EU/INS code for Sorbitan Monooleate. Emulsifier. Safe.',
    'e495': 'E495 is the EU/INS code for Sorbitan Monopalmitate. Emulsifier. Safe.',
    'diphosphates': 'Diphosphates (E450/INS 450, Pyrophosphates) are emulsifying salts in processed cheese and leavening agents in baking. Safe at approved levels.',
    'e450': 'E450 is the EU/INS code for Diphosphates (Pyrophosphates). Emulsifying salts in processed cheese. Safe at approved levels.',
    'e451': 'E451 is the EU/INS code for Triphosphates. Moisture-retaining agent in processed meats. Safe.',
    'e452': 'E452 is the EU/INS code for Polyphosphates. Emulsifying salts. Safe.',

    # ── Raising agents / minerals (E500-E599) ────────────────────────────
    'e500': 'E500 is the EU/INS code for Sodium Carbonates (including Baking Soda). Most widely used raising agent. Safe.',
    'sodium bicarbonate': 'Sodium Bicarbonate (Baking Soda/E500ii) is the most widely used leavening agent. Reacts with acids to release CO2 for rising. Safe.',
    'e501': 'E501 is the EU/INS code for Potassium Carbonates. Raising agent in cocoa and noodles. Safe.',
    'ammonium carbonate': 'Ammonium Carbonate (E503/INS 503, Bakers\' Ammonia) is a traditional raising agent for thin biscuits. Ammonia fully evaporates during baking. Safe.',
    'e503': 'E503 is the EU/INS code for Ammonium Carbonates. Traditional raising agent. Ammonia bakes out. Safe.',
    'magnesium carbonate': 'Magnesium Carbonate (E504/INS 504) is used as an anti-caking agent. Provides dietary magnesium. Safe.',
    'e504': 'E504 is the EU/INS code for Magnesium Carbonates. Anti-caking agent; provides magnesium. Safe.',
    'potassium chloride food': 'Potassium Chloride (E508/INS 508) is a low-sodium salt substitute and firming agent in tofu and vegetables. Provides dietary potassium. Safe.',
    'e508': 'E508 is the EU/INS code for Potassium Chloride. Low-sodium salt substitute. Safe.',
    'calcium chloride food': 'Calcium Chloride (E509/INS 509) is a firming agent in tofu, canned vegetables and cheese. Provides dietary calcium. Safe.',
    'e509': 'E509 is the EU/INS code for Calcium Chloride. Firming agent in tofu and vegetables. Safe.',
    'magnesium chloride food': 'Magnesium Chloride (E511/INS 511, Nigari) is the traditional Japanese tofu coagulant. Provides dietary magnesium. Safe.',
    'e511': 'E511 is the EU/INS code for Magnesium Chloride (Nigari). Traditional tofu coagulant. Safe.',
    'calcium sulphate food': 'Calcium Sulphate (E516/INS 516, food-grade gypsum) is a tofu coagulant and firming agent. Provides dietary calcium. Safe.',
    'e516': 'E516 is the EU/INS code for Calcium Sulphate (food-grade gypsum). Tofu coagulant. Safe.',
    'e524': 'E524 is the EU/INS code for Sodium Hydroxide (Lye). Processing aid for pretzels and olives; neutralised in final product. Safe.',
    'e525': 'E525 is the EU/INS code for Potassium Hydroxide. Processing aid in cocoa; neutralised in final product. Safe.',
    'e526': 'E526 is the EU/INS code for Calcium Hydroxide (Slaked Lime). Used in traditional nixtamalisation of corn; provides calcium. Safe.',
    'e530': 'E530 is the EU/INS code for Magnesium Oxide. Anti-caking agent; provides magnesium. Safe.',
    'silicon dioxide food': 'Silicon Dioxide (E551/INS 551, Amorphous Silica) is the most widely used anti-caking agent in powdered foods, salt and spices. Not absorbed by the body. Safe.',
    'e551': 'E551 is the EU/INS code for Silicon Dioxide (Amorphous Silica). Most widely used anti-caking agent. Not absorbed; safe.',
    'e552': 'E552 is the EU/INS code for Calcium Silicate. Anti-caking agent. Safe.',
    'e553a': 'E553a is the EU/INS code for Magnesium Silicates. Anti-caking agent. Safe.',
    'e572': 'E572 is the EU/INS code for Magnesium Stearate. Anti-caking agent in supplements. Safe.',
    'sodium ferrocyanide': 'Sodium Ferrocyanide (E535/INS 535) prevents table salt from clumping. Despite the name, the cyanide is firmly bound to iron and not released at food-use conditions. Safe in the tiny concentrations used in salt.',
    'e535': 'E535 is the EU/INS code for Sodium Ferrocyanide. Anti-caking agent in salt. Cyanide firmly bound -- safe at approved levels.',
    'e536': 'E536 is the EU/INS code for Potassium Ferrocyanide. Anti-caking agent in salt. Stable; safe.',
    'e558': 'E558 is the EU/INS code for Bentonite. Natural clay used to clarify wine; filtered out. Safe.',
    'e559': 'E559 is the EU/INS code for Kaolin (China Clay). Anti-caking agent. Safe.',

    # ── Flavour enhancers (E620-E650) ────────────────────────────────────
    'glutamic acid food': 'Glutamic Acid (E620/INS 620) is the naturally occurring amino acid responsible for umami taste in meat, cheese, tomatoes and mushrooms. Safe -- one of the most abundant amino acids in the diet.',
    'e620': 'E620 is the EU/INS code for Glutamic Acid. Natural amino acid responsible for umami taste. Safe.',
    'e622': 'E622 is the EU/INS code for Monopotassium Glutamate. Umami flavour enhancer. Safe.',
    'e623': 'E623 is the EU/INS code for Calcium Diglutamate. Umami flavour enhancer and calcium source. Safe.',
    'e624': 'E624 is the EU/INS code for Monoammonium Glutamate. Umami flavour enhancer. Safe.',
    'e625': 'E625 is the EU/INS code for Magnesium Diglutamate. Umami flavour enhancer. Safe.',
    'guanylic acid': 'Guanylic Acid (E626/INS 626) is a nucleotide from dried mushrooms and fish that amplifies umami. High purine content -- avoid with gout. Safe for most.',
    'e626': 'E626 is the EU/INS code for Guanylic Acid. Nucleotide umami enhancer; high purine -- avoid with gout.',
    'e628': 'E628 is the EU/INS code for Dipotassium Guanylate. Nucleotide flavour enhancer; avoid with gout.',
    'e629': 'E629 is the EU/INS code for Calcium Guanylate. Nucleotide flavour enhancer; avoid with gout.',
    'inosinic acid': 'Inosinic Acid (E630/INS 630) is a nucleotide from meat and fish. Umami taste enhancer. High purine -- avoid with gout. Safe for most.',
    'e630': 'E630 is the EU/INS code for Inosinic Acid. Nucleotide umami enhancer; avoid with gout.',
    'e632': 'E632 is the EU/INS code for Dipotassium Inosinate. Nucleotide flavour enhancer; avoid with gout.',
    'e633': 'E633 is the EU/INS code for Calcium Inosinate. Nucleotide flavour enhancer; avoid with gout.',
    'glycine food': 'Glycine (E640/INS 640) is the simplest amino acid, used as a mild sweetener and bitter masker. Naturally in gelatin and bone broth. Safe.',
    'e640': 'E640 is the EU/INS code for Glycine and its Sodium Salt. Amino acid flavour enhancer. Safe.',

    # ── Glazing agents / waxes / gases (E900-E999) ───────────────────────
    'dimethyl polysiloxane': 'Dimethyl Polysiloxane (PDMS/E900/INS 900) is a silicone polymer anti-foaming agent in frying oils and beverages. Not absorbed by the body. Safe.',
    'e900': 'E900 is the EU/INS code for Dimethyl Polysiloxane. Silicone anti-foaming agent. Safe.',
    'beeswax food': 'Beeswax (E901/INS 901) is natural wax from honeybees. Used as a glazing agent on confectionery and fruit. Safe; not vegan.',
    'e901': 'E901 is the EU/INS code for Beeswax. Natural glazing agent. Safe; not vegan.',
    'candelilla wax': 'Candelilla Wax (E902/INS 902) is a plant-based wax from the candelilla shrub. Vegan alternative to beeswax. Safe.',
    'e902': 'E902 is the EU/INS code for Candelilla Wax. Plant-based vegan glazing agent. Safe.',
    'carnauba wax food': 'Carnauba Wax (E903/INS 903) is the hardest natural wax from Brazilian carnauba palms. Gives shine to hard-coated sweets. Safe.',
    'e903': 'E903 is the EU/INS code for Carnauba Wax. The shine on hard-coated confectionery. Safe.',
    'shellac food': 'Shellac (E904/INS 904) is a natural resin from lac insects. High-gloss coating on confectionery and pharmaceutical tablets. Safe; not vegan. India is the world\'s largest producer.',
    'e904': 'E904 is the EU/INS code for Shellac. Insect-derived glazing agent. Safe; not vegan.',
    'e920': 'E920 is the EU/INS code for L-Cysteine. Dough conditioner amino acid. Often from hair/feathers -- check vegan status. Safe.',
    'e941': 'E941 is the EU/INS code for Nitrogen. Inert packaging gas. Safe -- makes up 78% of air.',
    'e942': 'E942 is the EU/INS code for Nitrous Oxide. Whipped cream propellant. Safe in food; dangerous recreationally.',

    # ── Sweeteners (E950-E968) ───────────────────────────────────────────
    'steviol glycosides': 'Steviol Glycosides (Stevia/E960/INS 960) are naturally sweet compounds from the stevia plant -- 200-400 times sweeter than sugar. Zero calories. Approved by FSSAI, FDA, EU and Codex. Safe; suitable for diabetics.',
    'e960': 'E960 is the EU/INS code for Steviol Glycosides (Stevia). Natural zero-calorie sweetener. Safe; suitable for diabetics.',
    'thaumatin': 'Thaumatin (E957/INS 957) is a natural sweet protein from the katemfe fruit -- about 2,500 times sweeter than sugar. Zero calories at use levels. Safe.',
    'e957': 'E957 is the EU/INS code for Thaumatin. Natural sweet protein; ~2,500x sweeter than sugar. Safe.',
    'neotame': 'Neotame (E961/INS 961) is an ultra-intense sweetener (~8,000x sweeter than sugar). Unlike aspartame, safe for phenylketonurics. FDA and EU approved.',
    'e961': 'E961 is the EU/INS code for Neotame. Ultra-intense sweetener. Safe for phenylketonurics. FDA and EU approved.',
    'e953': 'E953 is the EU/INS code for Isomalt. Sugar alcohol from sucrose; laxative at high intake; label warning required.',
    'e965': 'E965 is the EU/INS code for Maltitol. Sugar alcohol sweetener; laxative at >40g/day; label warning required.',
    'e966': 'E966 is the EU/INS code for Lactitol. Sugar alcohol; laxative at high intake; not for lactose-intolerant individuals.',
    'e967': 'E967 is the EU/INS code for Xylitol. Natural sugar alcohol with dental benefits. CAUTION -- toxic to dogs. Laxative effects in humans at high doses.',
    'erythritol': 'Erythritol (E968/INS 968) is a naturally occurring sugar alcohol from fermented foods. Near-zero calories; minimal laxative effect. Used in zero-calorie products. Safe.',
    'e968': 'E968 is the EU/INS code for Erythritol. Natural sugar alcohol; near-zero calories; minimal laxative effect. Safe.',
    'cyclamate': 'Cyclamate (E952/INS 952) is an artificial sweetener. Banned in USA (1969) and UK due to bladder cancer in rat studies. Permitted in India and EU at specified limits.',
    'e952': 'E952 is the EU/INS code for Cyclamate. Banned in USA and UK; permitted in India and EU at limits.',
    'sodium cyclamate': 'Sodium Cyclamate is the sodium salt form of cyclamate. Banned in USA and UK; approved in EU and India at limits.',

    # ── Modified starches (E1400-E1599) ──────────────────────────────────
    'e1404': 'E1404 is the EU/INS code for Oxidised Starch. Modified starch for confectionery coatings. Safe.',
    'e1410': 'E1410 is the EU/INS code for Monostarch Phosphate. Modified starch thickener. Safe.',
    'e1412': 'E1412 is the EU/INS code for Distarch Phosphate. Cross-linked modified starch. Safe.',
    'e1420': 'E1420 is the EU/INS code for Acetylated Starch. Modified starch. Safe.',
    'e1422': 'E1422 is the EU/INS code for Acetylated Distarch Adipate. Modified starch in soups and frozen foods. Safe.',
    'e1440': 'E1440 is the EU/INS code for Hydroxypropyl Starch. Modified starch. Safe.',
    'e1442': 'E1442 is the EU/INS code for Hydroxypropyl Distarch Phosphate. Widely used modified starch in ketchup, mayo and baby food. Safe.',
    'e1450': 'E1450 is the EU/INS code for Starch Sodium Octenyl Succinate. Emulsifying modified starch for encapsulating flavours. Safe.',
    'hydroxypropyl distarch phosphate': 'Hydroxypropyl Distarch Phosphate (E1442/INS 1442) has superior heat, acid and freeze-thaw stability. Widely used in ketchup, mayonnaise, sauces and baby food. Safe.',

    # ── INS number lookup entries ─────────────────────────────────────────
    'ins 100': 'INS 100 / E100 -- Curcumin (Turmeric Yellow). Natural yellow colour. Safe.',
    'ins 101': 'INS 101 / E101 -- Riboflavin (Vitamin B2). Natural yellow colour and B-vitamin. Safe.',
    'ins 102': 'INS 102 / E102 -- Tartrazine. Synthetic yellow azo dye. EU warning label required. See tartrazine.',
    'ins 110': 'INS 110 / E110 -- Sunset Yellow FCF. Synthetic orange azo dye. EU warning label required.',
    'ins 129': 'INS 129 / E129 -- Allura Red AC (Red 40). Synthetic red azo dye. EU warning label required.',
    'ins 150d': 'INS 150d / E150d -- Sulphite Ammonia Caramel. Contains 4-MEI (IARC Group 2B). See e150d.',
    'ins 160a': 'INS 160a / E160a -- Beta-Carotene. Natural orange-yellow colour; Vitamin A precursor. Safe.',
    'ins 160b': 'INS 160b / E160b -- Annatto. Natural orange colour. Safe.',
    'ins 162': 'INS 162 / E162 -- Beetroot Red (Betanin). Natural red-purple colour. Safe.',
    'ins 171': 'INS 171 / E171 -- Titanium Dioxide. White colour. BANNED in EU food since 2022.',
    'ins 200': 'INS 200 / E200 -- Sorbic Acid. Natural mould inhibitor. Safe.',
    'ins 202': 'INS 202 / E202 -- Potassium Sorbate. Most widely used food preservative. Safe.',
    'ins 211': 'INS 211 / E211 -- Sodium Benzoate. Preservative; forms benzene with Vitamin C. See sodium benzoate.',
    'ins 220': 'INS 220 / E220 -- Sulfur Dioxide. Preservative; triggers asthma in sensitive individuals. See sulfur dioxide.',
    'ins 250': 'INS 250 / E250 -- Sodium Nitrite. Meat curing agent; forms nitrosamines when heated. See sodium nitrite.',
    'ins 260': 'INS 260 / E260 -- Acetic Acid (Vinegar acid). Safe acidity regulator.',
    'ins 270': 'INS 270 / E270 -- Lactic Acid. Natural fermentation acid. Safe.',
    'ins 296': 'INS 296 / E296 -- Malic Acid. Natural apple acid. Safe.',
    'ins 300': 'INS 300 / E300 -- Ascorbic Acid (Vitamin C). Essential vitamin and antioxidant. Safe.',
    'ins 306': 'INS 306 / E306 -- Tocopherol (Vitamin E). Natural antioxidant. Safe.',
    'ins 320': 'INS 320 / E320 -- BHA. Synthetic antioxidant; IARC Group 2B possible carcinogen.',
    'ins 321': 'INS 321 / E321 -- BHT. Synthetic antioxidant; IARC possible carcinogen.',
    'ins 330': 'INS 330 / E330 -- Citric Acid. Natural fruit acid. Safe.',
    'ins 338': 'INS 338 / E338 -- Phosphoric Acid. Gives cola drinks their tang; erodes tooth enamel with heavy use.',
    'ins 400': 'INS 400 / E400 -- Alginic Acid. Natural seaweed thickener. Safe.',
    'ins 401': 'INS 401 / E401 -- Sodium Alginate. Seaweed gelling agent. Safe.',
    'ins 406': 'INS 406 / E406 -- Agar. Natural red algae gelling agent. Vegetarian gelatin. Safe.',
    'ins 407': 'INS 407 / E407 -- Carrageenan. Seaweed stabiliser. Gut inflammation concerns; banned in EU infant formula.',
    'ins 410': 'INS 410 / E410 -- Locust Bean Gum (Carob Gum). Natural seed thickener. Safe.',
    'ins 412': 'INS 412 / E412 -- Guar Gum. Natural Indian seed gum. Safe.',
    'ins 414': 'INS 414 / E414 -- Gum Arabic (Acacia Gum). Natural food gum. Safe.',
    'ins 415': 'INS 415 / E415 -- Xanthan Gum. Microbial thickener; key to gluten-free baking. Safe.',
    'ins 420': 'INS 420 / E420 -- Sorbitol. Sugar alcohol; laxative at >50g/day.',
    'ins 422': 'INS 422 / E422 -- Glycerol (Glycerine). Natural humectant. Safe.',
    'ins 433': 'INS 433 / E433 -- Polysorbate 80. Emulsifier; trace 1,4-dioxane possible. Safe within limits.',
    'ins 440': 'INS 440 / E440 -- Pectin. Natural gelling agent from citrus peel. Safe.',
    'ins 450': 'INS 450 / E450 -- Diphosphates. Emulsifying salts. Safe.',
    'ins 471': 'INS 471 / E471 -- Mono- and Diglycerides of Fatty Acids. Most widely used food emulsifier. Safe.',
    'ins 476': 'INS 476 / E476 -- PGPR. Chocolate emulsifier. Safe.',
    'ins 481': 'INS 481 / E481 -- Sodium Stearoyl Lactylate (SSL). Key bread emulsifier. Safe.',
    'ins 500': 'INS 500 / E500 -- Sodium Carbonates (Baking Soda). Most widely used raising agent. Safe.',
    'ins 508': 'INS 508 / E508 -- Potassium Chloride. Low-sodium salt substitute. Safe.',
    'ins 509': 'INS 509 / E509 -- Calcium Chloride. Firming agent. Safe.',
    'ins 511': 'INS 511 / E511 -- Magnesium Chloride (Nigari). Tofu coagulant. Safe.',
    'ins 516': 'INS 516 / E516 -- Calcium Sulphate. Tofu coagulant. Safe.',
    'ins 551': 'INS 551 / E551 -- Silicon Dioxide. Most widely used anti-caking agent. Not absorbed; safe.',
    'ins 575': 'INS 575 / E575 -- Glucono Delta-Lactone (GDL). Natural mild acidifier. Safe.',
    'ins 621': 'INS 621 / E621 -- Monosodium Glutamate (MSG). Umami flavour enhancer. FDA GRAS. Safe.',
    'ins 627': 'INS 627 / E627 -- Disodium Guanylate. Nucleotide flavour enhancer; avoid with gout.',
    'ins 631': 'INS 631 / E631 -- Disodium Inosinate. Nucleotide flavour enhancer; avoid with gout.',
    'ins 635': "INS 635 / E635 -- Disodium 5'-Ribonucleotides (I+G). Nucleotide enhancer blend; avoid with gout.",
    'ins 900': 'INS 900 / E900 -- Dimethyl Polysiloxane. Silicone anti-foaming agent. Safe.',
    'ins 903': 'INS 903 / E903 -- Carnauba Wax. Natural glazing agent. Safe.',
    'ins 951': 'INS 951 / E951 -- Aspartame. Artificial sweetener (IARC Group 2B). See aspartame.',
    'ins 954': 'INS 954 / E954 -- Saccharin. Artificial sweetener. Bladder cancer concerns. See saccharin.',
    'ins 955': 'INS 955 / E955 -- Sucralose. Artificial sweetener. See sucralose.',
    'ins 960': 'INS 960 / E960 -- Steviol Glycosides (Stevia). Natural zero-calorie sweetener. Safe.',
    'ins 967': 'INS 967 / E967 -- Xylitol. Sugar alcohol. TOXIC TO DOGS. Dental benefits for humans.',
    'ins 968': 'INS 968 / E968 -- Erythritol. Natural sugar alcohol; near-zero calories. Safe.',
    'ins 1442': 'INS 1442 / E1442 -- Hydroxypropyl Distarch Phosphate. Modified starch in ketchup and baby food. Safe.',
"""

src = src[:pos_desc_end] + new_entries + src[pos_desc_end:]
print(f"After desc additions: {src.count(chr(10))} lines")

# ── STEP 2: Remove e471 and mono and diglycerides from commonly_questioned ──
import re
# Remove the trans fats comment block and mono/diglycerides + e471 entries
pat1 = r"        # Trans fats.*?'mono and diglycerides',\n"
src = re.sub(pat1, "        # Trans fats -- banned USA/EU; cardiovascular risk\n        'partially hydrogenated','trans fat',\n", src, count=1, flags=re.DOTALL)

pat2 = r"        'e471': \('Mono- and Diglycerides of Fatty Acids \(E471\)'[^\n]+\n"
src = re.sub(pat2, '', src, count=1)

pat3 = r"        'mono and diglycerides': \('Emulsifier E471'[^\n]+\n"
src = re.sub(pat3, '', src, count=1)

print(f"After CQ removal: {src.count(chr(10))} lines")

with open('backend/routes/ingredient_database.py', 'w', encoding='utf-8') as f:
    f.write(src)
print("Done")
