"""Script to insert all missing ingredient entries into product_ingredients_full.py"""

new_entries = """
    # HONEY & SPREADS
    "dabur-honey": [
        create_ingredient_item("Pure Honey"),
    ],
    "patanjali-honey": [
        create_ingredient_item("Pure Honey"),
    ],
    "kissan-jam": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Apple Pulp"),
        create_ingredient_item("Banana Pulp"),
        create_ingredient_item("Papaya Pulp"),
        create_ingredient_item("Pineapple Pulp"),
        create_ingredient_item("Mango Pulp"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Pectin"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    "nutella": [
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palm Oil"),
        create_ingredient_item("Hazelnuts"),
        create_ingredient_item("Skimmed Milk Powder"),
        create_ingredient_item("Cocoa Powder"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Vanillin"),
    ],
    "fortune-sunflower-oil": [
        create_ingredient_item("Refined Sunflower Oil"),
    ],
    "saffola-gold": [
        create_ingredient_item("Refined Rice Bran Oil"),
        create_ingredient_item("Refined Sunflower Oil"),
    ],
    "dhara-mustard-oil": [
        create_ingredient_item("Refined Mustard Oil"),
    ],
    "fortune-rice-bran": [
        create_ingredient_item("Refined Rice Bran Oil"),
    ],
    "saffola-tasty": [
        create_ingredient_item("Refined Corn Oil"),
        create_ingredient_item("Refined Soybean Oil"),
    ],
    "patanjali-mustard-oil": [
        create_ingredient_item("Mustard Oil"),
    ],
    "mdh-chana-masala": [
        create_ingredient_item("Coriander"),
        create_ingredient_item("Cumin"),
        create_ingredient_item("Dry Mango"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Red Chilli"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Dry Ginger"),
        create_ingredient_item("Pomegranate Seeds"),
        create_ingredient_item("Cloves"),
        create_ingredient_item("Cardamom"),
        create_ingredient_item("Asafoetida"),
    ],
    "mdh-garam-masala": [
        create_ingredient_item("Coriander"),
        create_ingredient_item("Cumin"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Cloves"),
        create_ingredient_item("Cardamom"),
        create_ingredient_item("Mace"),
        create_ingredient_item("Nutmeg"),
        create_ingredient_item("Bay Leaves"),
    ],
    "everest-garam-masala": [
        create_ingredient_item("Coriander"),
        create_ingredient_item("Cumin"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Cassia"),
        create_ingredient_item("Cloves"),
        create_ingredient_item("Cardamom"),
        create_ingredient_item("Mace"),
        create_ingredient_item("Nutmeg"),
        create_ingredient_item("Bay Leaves"),
    ],
    "everest-chana-masala": [
        create_ingredient_item("Coriander"),
        create_ingredient_item("Cumin"),
        create_ingredient_item("Dry Mango"),
        create_ingredient_item("Red Chilli"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Cardamom"),
        create_ingredient_item("Cloves"),
    ],
    "catch-turmeric": [
        create_ingredient_item("Turmeric"),
    ],
    "mdh-rajma-masala": [
        create_ingredient_item("Coriander"),
        create_ingredient_item("Cumin"),
        create_ingredient_item("Red Chilli"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Turmeric"),
        create_ingredient_item("Garam Masala"),
    ],
    "everest-kitchen-king": [
        create_ingredient_item("Coriander"),
        create_ingredient_item("Cumin"),
        create_ingredient_item("Turmeric"),
        create_ingredient_item("Red Chilli"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Black Pepper"),
        create_ingredient_item("Cardamom"),
        create_ingredient_item("Cloves"),
        create_ingredient_item("Mace"),
    ],
    "patanjali-haldi": [
        create_ingredient_item("Turmeric"),
    ],
    "mtr-paneer-butter-masala": [
        create_ingredient_item("Water"),
        create_ingredient_item("Paneer"),
        create_ingredient_item("Tomato Paste"),
        create_ingredient_item("Onion"),
        create_ingredient_item("Butter"),
        create_ingredient_item("Cashew Paste"),
        create_ingredient_item("Cream"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Refined Sunflower Oil"),
        create_ingredient_item("Ginger"),
        create_ingredient_item("Garlic"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Citric Acid"),
    ],
    "mtr-dal-makhani": [
        create_ingredient_item("Water"),
        create_ingredient_item("Black Lentils"),
        create_ingredient_item("Kidney Beans"),
        create_ingredient_item("Tomato Paste"),
        create_ingredient_item("Butter"),
        create_ingredient_item("Cream"),
        create_ingredient_item("Onion"),
        create_ingredient_item("Ginger"),
        create_ingredient_item("Garlic"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Spices"),
    ],
    "mtr-palak-paneer": [
        create_ingredient_item("Water"),
        create_ingredient_item("Spinach"),
        create_ingredient_item("Paneer"),
        create_ingredient_item("Onion"),
        create_ingredient_item("Tomato"),
        create_ingredient_item("Cream"),
        create_ingredient_item("Refined Oil"),
        create_ingredient_item("Ginger"),
        create_ingredient_item("Garlic"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Spices"),
    ],
    "haldiram-ready-to-eat": [
        create_ingredient_item("Potatoes"),
        create_ingredient_item("Tomatoes"),
        create_ingredient_item("Onion"),
        create_ingredient_item("Refined Oil"),
        create_ingredient_item("Butter"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Citric Acid"),
    ],
    "aashirvaad-atta": [
        create_ingredient_item("Whole Wheat Flour"),
    ],
    "pillsbury-atta": [
        create_ingredient_item("Whole Wheat Flour"),
    ],
    "patanjali-atta": [
        create_ingredient_item("Whole Wheat Flour"),
    ],
    "aashirvaad-multigrain": [
        create_ingredient_item("Whole Wheat Flour"),
        create_ingredient_item("Soya Flour"),
        create_ingredient_item("Oat Flour"),
        create_ingredient_item("Maize Flour"),
        create_ingredient_item("Psyllium Husk"),
    ],
    "maggi-ketchup": [
        create_ingredient_item("Tomato Paste"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Water"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Acetic Acid"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Modified Starch"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    "kissan-ketchup": [
        create_ingredient_item("Tomatoes"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Acetic Acid"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    "veeba-mayo": [
        create_ingredient_item("Refined Soybean Oil"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Egg Yolk"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Acetic Acid"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Xanthan Gum"),
        create_ingredient_item("Potassium Sorbate"),
        create_ingredient_item("Calcium Disodium EDTA"),
    ],
    "dr-oetker-mayo": [
        create_ingredient_item("Refined Soybean Oil"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Egg Yolk"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Acetic Acid"),
        create_ingredient_item("Xanthan Gum"),
        create_ingredient_item("Calcium Disodium EDTA"),
    ],
    "maggi-hot-sweet": [
        create_ingredient_item("Tomato Paste"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Water"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Chilli"),
        create_ingredient_item("Acetic Acid"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    "kelloggs-corn-flakes": [
        create_ingredient_item("Milled Corn"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Malt Flavouring"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Minerals"),
    ],
    "kelloggs-chocos": [
        create_ingredient_item("Wheat Flour"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Edible Vegetable Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Soy Lecithin"),
    ],
    "kelloggs-muesli": [
        create_ingredient_item("Rolled Oats"),
        create_ingredient_item("Wheat Flakes"),
        create_ingredient_item("Raisins"),
        create_ingredient_item("Almonds"),
        create_ingredient_item("Cashews"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Salt"),
    ],
    "quaker-oats": [
        create_ingredient_item("Whole Grain Rolled Oats"),
    ],
    "bagrry-corn-flakes": [
        create_ingredient_item("Corn"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Malt Extract"),
        create_ingredient_item("Salt"),
    ],
    "saffola-oats": [
        create_ingredient_item("Whole Grain Oats"),
    ],
    "real-mango": [
        create_ingredient_item("Water"),
        create_ingredient_item("Mango Pulp"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Ascorbic Acid"),
        create_ingredient_item("Pectin"),
        create_ingredient_item("Natural Flavour"),
    ],
    "real-apple": [
        create_ingredient_item("Water"),
        create_ingredient_item("Apple Juice Concentrate"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Ascorbic Acid"),
        create_ingredient_item("Natural Flavour"),
    ],
    "tropicana-orange": [
        create_ingredient_item("Orange Juice"),
    ],
    "paper-boat-aamras": [
        create_ingredient_item("Mango Pulp"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Ascorbic Acid"),
    ],
    "paper-boat-jaljeera": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Cumin"),
        create_ingredient_item("Mint"),
        create_ingredient_item("Black Salt"),
        create_ingredient_item("Ginger"),
        create_ingredient_item("Citric Acid"),
    ],
    "b-natural-mango": [
        create_ingredient_item("Mango Pulp"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Ascorbic Acid"),
    ],
    "amul-vanilla": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Edible Vegetable Oil"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Locust Bean Gum"),
        create_ingredient_item("Carrageenan"),
        create_ingredient_item("Natural Vanilla Flavour"),
    ],
    "amul-chocolate": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Edible Vegetable Oil"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Carrageenan"),
        create_ingredient_item("Artificial Chocolate Flavour"),
    ],
    "kwality-walls-cornetto": [
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Edible Vegetable Oil"),
        create_ingredient_item("Glucose Syrup"),
        create_ingredient_item("Cocoa Solids"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Carrageenan"),
        create_ingredient_item("Artificial Flavours"),
    ],
    "mother-dairy-kulfi": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Cardamom"),
        create_ingredient_item("Saffron"),
        create_ingredient_item("Guar Gum"),
    ],
    "havmor-ice-cream": [
        create_ingredient_item("Milk"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Solids"),
        create_ingredient_item("Edible Vegetable Oil"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Guar Gum"),
        create_ingredient_item("Carrageenan"),
        create_ingredient_item("Natural Vanilla Flavour"),
    ],
    "priya-mango-pickle": [
        create_ingredient_item("Mango"),
        create_ingredient_item("Refined Rice Bran Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Red Chilli Powder"),
        create_ingredient_item("Mustard"),
        create_ingredient_item("Fenugreek"),
        create_ingredient_item("Turmeric"),
        create_ingredient_item("Asafoetida"),
        create_ingredient_item("Acetic Acid"),
    ],
    "mothers-recipe-pickle": [
        create_ingredient_item("Mango"),
        create_ingredient_item("Lime"),
        create_ingredient_item("Carrot"),
        create_ingredient_item("Chilli"),
        create_ingredient_item("Refined Sunflower Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Spices"),
        create_ingredient_item("Acetic Acid"),
    ],
    "patanjali-mango-pickle": [
        create_ingredient_item("Mango"),
        create_ingredient_item("Mustard Oil"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Red Chilli"),
        create_ingredient_item("Turmeric"),
        create_ingredient_item("Fenugreek"),
        create_ingredient_item("Asafoetida"),
    ],
    "britannia-bread": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Yeast"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Gluten"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("DATEM"),
        create_ingredient_item("Ascorbic Acid"),
    ],
    "modern-bread": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Edible Vegetable Fat"),
        create_ingredient_item("Yeast"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Gluten"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Calcium Propionate"),
    ],
    "harvest-gold-bread": [
        create_ingredient_item("Refined Wheat Flour"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Edible Vegetable Fat"),
        create_ingredient_item("Yeast"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Gluten"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Calcium Propionate"),
    ],
    "britannia-whole-wheat-bread": [
        create_ingredient_item("Whole Wheat Flour"),
        create_ingredient_item("Water"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Palmolein Oil"),
        create_ingredient_item("Yeast"),
        create_ingredient_item("Salt"),
        create_ingredient_item("Gluten"),
        create_ingredient_item("Mono and Diglycerides"),
        create_ingredient_item("Ascorbic Acid"),
    ],
    "tata-tea-gold": [
        create_ingredient_item("Black Tea"),
    ],
    "tata-tea-premium": [
        create_ingredient_item("Black Tea"),
    ],
    "red-label-tea": [
        create_ingredient_item("Black Tea"),
        create_ingredient_item("Tulsi"),
        create_ingredient_item("Ginger"),
        create_ingredient_item("Cardamom"),
        create_ingredient_item("Ashwagandha"),
        create_ingredient_item("Mulethi"),
    ],
    "nescafe-classic": [
        create_ingredient_item("Coffee"),
    ],
    "bru-coffee": [
        create_ingredient_item("Coffee"),
        create_ingredient_item("Chicory"),
    ],
    "tata-coffee": [
        create_ingredient_item("Coffee"),
    ],
    "green-tea-lipton": [
        create_ingredient_item("Green Tea"),
    ],
    "himalaya-face-wash": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Neem Extract"),
        create_ingredient_item("Turmeric Extract"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    "garnier-men-face-wash": [
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Coco-Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Charcoal Powder"),
        create_ingredient_item("Salicylic Acid"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Fragrance"),
    ],
    "neutrogena-face-wash": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Salicylic Acid"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Fragrance"),
    ],
    "cetaphil-face-wash": [
        create_ingredient_item("Water"),
        create_ingredient_item("Cetyl Alcohol"),
        create_ingredient_item("Propylene Glycol"),
        create_ingredient_item("Sodium Lauryl Sulfate"),
        create_ingredient_item("Stearyl Alcohol"),
        create_ingredient_item("Methylparaben"),
        create_ingredient_item("Propylparaben"),
        create_ingredient_item("Butylparaben"),
    ],
    "ponds-face-wash": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Citric Acid"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    "lakme-face-wash": [
        create_ingredient_item("Water"),
        create_ingredient_item("Sodium Laureth Sulfate"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Fruit Extracts"),
        create_ingredient_item("Sodium Chloride"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Citric Acid"),
    ],
    "nivea-cream": [
        create_ingredient_item("Water"),
        create_ingredient_item("Mineral Oil"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Lanolin Alcohol"),
        create_ingredient_item("Paraffin"),
        create_ingredient_item("Panthenol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Citric Acid"),
    ],
    "vaseline-lotion": [
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Stearic Acid"),
        create_ingredient_item("Petroleum Jelly"),
        create_ingredient_item("Dimethicone"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Sodium Hydroxide"),
    ],
    "himalaya-moisturizer": [
        create_ingredient_item("Water"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Aloe Vera"),
        create_ingredient_item("Winter Cherry Extract"),
        create_ingredient_item("Indian Pennywort Extract"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    "ponds-cold-cream": [
        create_ingredient_item("Water"),
        create_ingredient_item("Mineral Oil"),
        create_ingredient_item("Beeswax"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Sodium Borate"),
    ],
    "lakme-sunscreen": [
        create_ingredient_item("Water"),
        create_ingredient_item("Ethylhexyl Methoxycinnamate"),
        create_ingredient_item("Titanium Dioxide"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Dimethicone"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Sodium Benzoate"),
    ],
    "surf-excel-matic": [
        create_ingredient_item("Anionic Surfactants"),
        create_ingredient_item("Non-Ionic Surfactants"),
        create_ingredient_item("Soap"),
        create_ingredient_item("Enzymes"),
        create_ingredient_item("Optical Brightener"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Water"),
    ],
    "ariel-matic": [
        create_ingredient_item("Anionic Surfactants"),
        create_ingredient_item("Non-Ionic Surfactants"),
        create_ingredient_item("Enzymes"),
        create_ingredient_item("Optical Brightener"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Carbonate"),
    ],
    "tide-plus": [
        create_ingredient_item("Anionic Surfactants"),
        create_ingredient_item("Non-Ionic Surfactants"),
        create_ingredient_item("Soap"),
        create_ingredient_item("Enzymes"),
        create_ingredient_item("Optical Brightener"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Carbonate"),
        create_ingredient_item("Sodium Sulfate"),
    ],
    "rin-detergent": [
        create_ingredient_item("Anionic Surfactants"),
        create_ingredient_item("Non-Ionic Surfactants"),
        create_ingredient_item("Soap"),
        create_ingredient_item("Optical Brightener"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Carbonate"),
    ],
    "wheel-detergent": [
        create_ingredient_item("Anionic Surfactants"),
        create_ingredient_item("Non-Ionic Surfactants"),
        create_ingredient_item("Soap"),
        create_ingredient_item("Perfume"),
        create_ingredient_item("Sodium Carbonate"),
    ],
    "johnsons-baby-shampoo": [
        create_ingredient_item("Water"),
        create_ingredient_item("PEG-80 Sorbitan Laurate"),
        create_ingredient_item("Sodium Trideceth Sulfate"),
        create_ingredient_item("PEG-150 Distearate"),
        create_ingredient_item("Cocamidopropyl Betaine"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Citric Acid"),
    ],
    "johnsons-baby-lotion": [
        create_ingredient_item("Water"),
        create_ingredient_item("Mineral Oil"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Cetyl Alcohol"),
        create_ingredient_item("Fragrance"),
        create_ingredient_item("Sodium Benzoate"),
        create_ingredient_item("Citric Acid"),
    ],
    "himalaya-baby-soap": [
        create_ingredient_item("Soap Noodles"),
        create_ingredient_item("Olive Oil"),
        create_ingredient_item("Aloe Vera Extract"),
        create_ingredient_item("Glycerin"),
        create_ingredient_item("Fragrance"),
    ],
    "ensure-nutrition": [
        create_ingredient_item("Corn Maltodextrin"),
        create_ingredient_item("Sugar"),
        create_ingredient_item("Milk Protein Concentrate"),
        create_ingredient_item("Soy Oil"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Vitamins"),
        create_ingredient_item("Minerals"),
        create_ingredient_item("Artificial Flavour"),
    ],
    "whey-protein-muscleblaze": [
        create_ingredient_item("Whey Protein Concentrate"),
        create_ingredient_item("Whey Protein Isolate"),
        create_ingredient_item("Soy Lecithin"),
        create_ingredient_item("Sucralose"),
        create_ingredient_item("Artificial Flavour"),
    ],
    "sattu-patanjali": [
        create_ingredient_item("Roasted Gram Flour"),
    ],
"""

filepath = 'routes/product_ingredients_full.py'
content = open(filepath, 'r', encoding='utf-8').read()

insert_marker = '\n}\n\n# For products not in FULL_INGREDIENTS'
idx = content.find(insert_marker)
if idx == -1:
    print('ERROR: Could not find insertion point')
else:
    new_content = content[:idx] + new_entries + content[idx:]
    open(filepath, 'w', encoding='utf-8').write(new_content)
    print(f'SUCCESS: Inserted entries for {new_entries.count(chr(34)+":") } products')
